<?
$PERM["search"]["5"]="W";
$PERM["auth"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["project"]["5"]="W";
$PERM["price"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>